import { Inter } from "next/font/google";
import { Raleway } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const raleway_init = Raleway({
  subsets: ["latin"],
  weights: [100, 200, 300, 400, 500, 600, 700],
  variable: "--font-raleway",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway_init.variable}>{children}</body>
    </html>
  );
}
