import { Inter } from "next/font/google";
import { Raleway } from "next/font/google";
import "./globals.css";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import SessionProvider from "./SessionProvider";
import Login from "./login/page";
import Home from "./page";
import Register from "./register/page";
import Dashboard from "./dashboard/page";

const inter = Inter({ subsets: ["latin"] });

const raleway_init = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-raleway",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={raleway_init.variable}>
        <SessionProvider session={session}>
          {!session ? (
            <>
              <Home />
              <Login />
              <Register />
            </>
          ) : (
            <>
              <Dashboard />
              {children}
            </>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
